version: '3'

services:
  selenium-hub:
    image: seleniarm/hub:4.17.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  selenium-node:
    image: seleniarm/node-chromium:4.17.0
    container_name: selenium-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - /dev/shm:/dev/shm

  webapp:
    build: .
    container_name: webapp
    depends_on:
      - selenium-hub
      - selenium-node
    environment:
      - SELENIUM_REMOTE_URL=http://selenium-hub:4444
      - PYTHONPATH=.
    command: >
      bash -c "sleep 10 && python tests_runner/ui_test_runner.py"